#!/usr/bin/env node
/* Computes the exact probability of every badge and the EP distribution over every possible roll,
   then writes data/rarity.js. Run it after changing badges.js or config.js:   node tools/compute-rarity.js
   Takes about half a minute for 0..1,000,000. */
var path = require('path'), fs = require('fs');
var dir = path.join(__dirname, '..');
var CONFIG = require(path.join(dir, 'config.js'));
var B = require(path.join(dir, 'badges.js'));
var E = require(path.join(dir, 'engine.js'));
var max = CONFIG.max, total = max + 1;
var ids = B.BADGES.map(function (b) { return b.id; });
var index = {}; ids.forEach(function (id, i) { index[id] = i; });
var counts = new Float64Array(ids.length);
var perNumber = new Array(total); // badge index lists, so the second pass is cheap
var t0 = Date.now();
for (var n = 0; n <= max; n++) {
  var h = E.hits(n), arr = new Uint8Array(h.length);
  for (var i = 0; i < h.length; i++) { arr[i] = index[h[i].badge.id]; counts[arr[i]]++; }
  perNumber[n] = arr;
  if (n % 100000 === 0) process.stdout.write('\r  analysed ' + n.toLocaleString() + ' / ' + total.toLocaleString());
}
console.log('\r  analysed ' + total.toLocaleString() + ' numbers in ' + ((Date.now() - t0) / 1000).toFixed(1) + ' s');
var p = {}, ep = {};
ids.forEach(function (id, i) { p[id] = counts[i] / total; ep[id] = E.epFor(p[id], CONFIG); });
var eps = new Float64Array(total);
for (var m = 0; m <= max; m++) { var t = 0, a = perNumber[m]; for (var j = 0; j < a.length; j++) t += ep[ids[a[j]]]; eps[m] = t; }
var sorted = Float64Array.from(eps).sort();
var quantiles = []; for (var q = 0; q <= 1000; q++) quantiles.push(sorted[Math.floor(q / 1000 * (total - 1))]);
var best = 0; for (var k = 0; k <= max; k++) if (eps[k] > eps[best]) best = k;
var out = { max: max, epPerProbability: CONFIG.epPerProbability || 100, generatedAt: new Date().toISOString(), badges: ids.length, p: p, count: {}, quantiles: quantiles, bestRoll: { n: best, ep: eps[best] } };
ids.forEach(function (id, i) { out.count[id] = counts[i]; });
var js = '/* Generated by tools/compute-rarity.js — do not edit by hand. Rerun the tool after changing badges.js. */\n' +
  '(function (root) { var R = ' + JSON.stringify(out) + '; if (typeof module !== "undefined" && module.exports) module.exports = R; root.RNG_RARITY = R; })(typeof window !== "undefined" ? window : globalThis);\n';
fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
fs.writeFileSync(path.join(dir, 'data', 'rarity.js'), js);
console.log('  wrote data/rarity.js (' + ids.length + ' badges)\n');
console.log('  badge'.padEnd(28) + 'tier'.padEnd(10) + 'probability'.padEnd(14) + 'EP');
B.BADGES.slice().sort(function (a, b) { return p[b.id] - p[a.id]; }).forEach(function (b) {
  var pr = p[b.id], tier = pr > 0 ? E.badgeTier(pr).name : 'never';
  console.log('  ' + (b.emoji + ' ' + b.name).padEnd(26) + tier.padEnd(10) + (pr > 0 ? (pr * 100).toPrecision(3) + '%' : '0').padEnd(14) + (pr > 0 ? ep[b.id].toLocaleString() : '-'));
});
console.log('\n  best possible roll: ' + best + ' with ' + eps[best].toLocaleString() + ' EP; median roll ' + quantiles[500].toLocaleString() + ' EP');
